version: '3'

services:

    agent:
      image: duckietown/dt-notebook:daffy
      build:
          context: .
          dockerfile: setup/Dockerfile
      working_dir: /duckietown
      networks: &networks
        - duckietown-docker-net
      env_file: &env_file
        - setup/parameters.env
      volumes:
        - fifos:/fifos
      environment:
        - "HOSTNAME=default"
        - "VEHICLE_NAME=default"
        - "DISPLAY=:99"
        - "AIDONODE_DATA_IN=/fifos/agent-in"
        - "AIDONODE_DATA_OUT=fifo:/fifos/agent-out"
      expose:
        - "8888"
        - "5233"
      ports:
        - "8888:8888"

          #novnc:
          #  image: duckietown/docker-ros-vnc:daffy
          #  networks: *networks
          #  env_file: *env_file
          #  environment:
          #  - "ROS_MASTER_URI=http://ros_core:11311"
          #  - "HOSTNAME=default"
          #  - "VEHICLE_NAME=default"
          #  expose:
          #  - "5901"
          #  - "6901"
          #  ports:
          #  - "5901:5901"
          #  - "6901:6901"

    simulator:
      #image: courchesnea/dt-simbridge:test
      #image: duckietown/challenge-aido_lf-simulator-gym:daffy-aido4
      #TODO change this to duckietown/...:mooc-exercises
      image: courchesnea/challenge-aido_lf-simulator-gym:mooc-exercises
      #build:
      #    context: setup/challenge-aido_LF-simulator-gym/
      #    dockerfile: Dockerfile
      environment:
        AIDONODE_DATA_IN: /fifos/simulator-in
        AIDONODE_DATA_OUT: fifo:/fifos/simulator-out
        AIDONODE_CONFIG: |
          env_constructor: Simulator
          env_parameters:
            max_steps: 500001 # we don't want the gym to reset itself
            camera_width: 640 
            camera_height: 480
            #camera_width: 320
            #camera_height: 240
      volumes:
        - fifos:/fifos
      networks: *networks
      env_file: *env_file

    middleware_manager:
      #image: courchesnea/fifos-connector:daffy-aido4
      build:
        context: setup/fifos-connector/
        dockerfile: Dockerfile
      environment:
        middleware_parameters: |
          episodes_per_scenario: 1
          episode_length_s: 100.0
          min_episode_length_s: 1.0 
          seed: 42
          physics_dt: 0.05
          max_failures: 2
          agent_in: /fifos/agent-in
          agent_out: /fifos/agent-out
          sim_in: /fifos/simulator-in
          sim_out: /fifos/simulator-out
          sm_in: None
          sm_out: None
          timeout_initialization: 15
          timeout_regular: 360
          #ROS_MASTER_URI: "http://ros_master:11311"
      volumes:
        - fifos:/fifos
      networks: *networks
      env_file: *env_file

volumes:
  fifos:

networks:
    duckietown-docker-net:
